### ISSUE TITLE
Compliance Status

### ISSUE THREAD

**Issue by gyh1997127** [taneroksuz/riscv-fpu#2]
Hi,

Could you speak about the compliance status of the FPU? Does it support denormals? Does FMA truncate multiplier's intermediate results? Much appreciated!

**Comment by taneroksuz** [comment]
Hi,

The FPU covers all operations of IEEE 754 defined by RISCV ISA. This library can be verified with testcases generated by Berkeley-Testfloat. These testcases also contains subnormals (denormals). But this FPU gives only canonical form of NaN (not a number) as result if the originaly output of the operation is NaN. So I have build some logic in testbench to compare correctly the ouputs of testcases and this FPU in case of NaN generation. This case was also mentioned already in documentation of this FPU. The FMA unit does not truncate multiplier's intermediate results because this information is necessary for the correct output of these FMA operations.

Best Regards
